kind: template
load: nodeProject.jsonnet
data:
    config: |
            {
                "environmentVariables": [
                    "PGWC_PORTAINER_HOST",
                    "PGWC_PORTAINER_TOKEN"
                ],
                "docker": {
                    "host": "chronos.dasred.de",
                    "port": 6000,
                    "labels": {
                        "grafana.display": true,
                        "grafana.name": "Portainer Github Connector"
                    }
                }
            }
